# Site Settings
name        : "yk"
real_name   : "王磊"
email       : "m8524769@163.com"
title       : "Blog"
SEO_title   : "yk's Blog | 王磊的博客"
separator   : "'s "
description : "DO WHAT YOU CAN'T"
greeting    : "Hey Bro, Fantastic to have you here!"
url         : "https://m8524769.github.io"
github      : "m8524769"
github_url  : "https://github.com/m8524769"

plugins:
  - jekyll-octicons

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
