# Site Settings
email       : "m8524769@163.com"
name        : "yk"
title       : "Github Page"
separator   : "|"
description : "Hey Bro, Fantastic to have you here!"
url         : "https://m8524769.github.io"
github      : "m8524769"
github_url  : "https://github.com/m8524769"


# Nav List
menu:
- {name: Home, url: '#'}
- {name: Blog, url: '#blog'}
- {name: About Me, url: '#about'}


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
